"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../../.next/static/css/e0f73cd6f96bcb37.css"; // Ensure this path is correct based on your project structure
import "../../public/js/css/e0f73cd6f96bcb37.css";
import MainLayout from "@/layouts/MainLayout";
import Script from "next/script";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>
         SmarTech Locks - Smart Electronic Lock Company, Smart Lock Companies, Digital Door Lock Company Door Lock Lock Factory Door Factory Smart Door Lock Door Lock Custom Door Lock OEM TENON SMART
        </title>
        <meta
          name="description"
          content="TENON is a leading smart locks company in China. We provide a variety of smart locks wholesale, which can be employed in various scenarios such as real estate projects, residences, offices, etc. First-class research centers & high-standard dust-free workshop. Choose reliable smart lock supplier now!"
        />
        <meta
          name="keywords"
          content="smart electronic lock company, smart lock companies, digital door lock company door lock lock factory door factory Smart Door Lock door lock custom door lock oem TENON SMART News & Media"
        />
        <meta name="robots" content="noodp" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="shortcut icon" href="favicon.ico" />
        <meta property="og:locale" content="en" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Digital Electronic Smart Door Lock Wholesale Manufacturer/Supplier/Factory China | Tenon Lock"
        />
        <meta
          property="og:description"
          content="TENON is a leading smart locks company in China. We provide a variety of smart locks wholesale, which can be employed in various scenarios such as real estate projects, residences, offices, etc. First-class research centers & high-standard dust-free workshop. Choose reliable smart lock supplier now!"
        />
        {/* <meta property="og:url" content="index.html" /> */}
        <meta
          property="og:site_name"
          content="Guangdong AP Tenon Sci.& Tech. Co., Ltd."
        />
        <meta name="twitter:card" content="summary" />
        <meta
          name="twitter:site"
          content="@Guangdong AP Tenon Sci.& Tech. Co., Ltd."
        />
        <meta
          name="twitter:description"
          content="TENON is a leading smart locks company in China. We provide a variety of smart locks wholesale, which can be employed in various scenarios such as real estate projects, residences, offices, etc. First-class research centers & high-standard dust-free workshop. Choose reliable smart lock supplier now!"
        />
        <meta
          name="twitter:title"
          content="Digital Electronic Smart Door Lock Wholesale Manufacturer/Supplier/Factory China | Tenon Lock"
        />
        <link rel="canonical" href="index.html" />
        <Script type="application/ld+json">
          {JSON.stringify({
            "@context": "http://schema.org",
            "@type": "WebSite",
            "@id": "#website",
            url: "https://www.aptenontech.com/",
            name: "Guangdong AP Tenon Sci.& Tech. Co., Ltd.",
            potentialAction: {
              "@type": "SearchAction",
              target:
                "https://www.aptenontech.com/search?q={search_term_string}",
              "query-input": "required name=search_term_string",
            },
          })}
        </Script>
        <Script type="application/ld+json">
          {JSON.stringify({
            "@context": "http://schema.org",
            "@type": "Organization",
            url: "https://www.aptenontech.com",
            logo: "https://www.aptenontech.com/uploads/image/20220331/09/tenon-smart-lock.png",
            address: {
              "@type": "PostalAddress",
              addressLocality: "Guangzhou",
              addressRegion: "Guangdong",
              streetAddress: "",
              postalCode: "511400",
            },
            contactPoint: [
              {
                "@type": "ContactPoint",
                telephone: "",
                contactType: "customer service",
                areaServed: "China",
                availableLanguage: ["English"],
              },
            ],
            sameAs: [
              "https://www.facebook.com/tenontech",
              "https://www.linkedin.com/company/tenontech",
            ],
            potentialAction: {
              "@type": "SearchAction",
              target: "https://www.aptenontech.com/search?q={query}",
              query: "required",
            },
          })}
        </Script>
        <link
          href="/themes/tianxing/css/index.min.css"
          rel="stylesheet"
          type="text/css"
        />
        <link rel="stylesheet" href="/themes/tianxing/css/all.min.css" />
        <link rel="stylesheet" href="/themes/tianxing/swiper/swiper.min.css" />
        <Script src="/themes/tianxing/swiper/jquery-1.10.2.min.js"></Script>
        <Script src="/themes/tianxing/swiper/swiper-bundle.min.js"></Script>
        <Script src="/themes/tianxing/swiper/swiper.min.js"></Script>
        <Script src="/themes/tianxing/swiper/jquery.zoom.min.js"></Script>
        <Script src="/assets/js/seajs/sea.js"></Script>
        <Script src="/assets/js/html5shiv.min.js"></Script>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=UA-150725497-11"
        ></Script>
        <Script>{`window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'UA-150725497-11');
    gtag('event', 'conversion', { 'send_to': 'AW-10864103643/xtzNCNiqmbUDENuhtLwo' });
    gtag('config', 'AW-10864103643');`}</Script>
        <Script>{`(function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
      var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
      j.async = true; j.src = '../www.googletagmanager.com/gtm5445.html?id=' + i + dl;
      f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-TQRM47B');`}</Script>
        <Script>{`(function (h, o, t, j, a, r) {
      h.hj = h.hj || function () { (h.hj.q = h.hj.q || []).push(arguments) };
      h._hjSettings = { hjid: 3204671, hjsv: 6 };
      a = o.getElementsByTagName('head')[0];
      r = o.createElement('script'); r.async = 1;
      r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
      a.appendChild(r);
    })(window, document, 'https://static.hotjar.com/c/hotjar-', '.js?sv=');`}</Script>
        <Script>{`!function (f, b, e, v, n, t, s) {
      if (f.fbq) return; n = f.fbq = function () {
        n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments)
      };
      if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
      n.queue = []; t = b.createElement(e); t.async = !0;
      t.src = v; s = b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t, s)
    }(window, document, 'script', '../connect.facebook.net/en_US/fbevents.js');
    fbq('init', '673383750668124');
    fbq('track', 'PageView');`}</Script>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-11513643654"
        ></Script>
        <Script>{`window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'AW-11513643654');`}</Script>
        <style>{`
    .sep-body .body_tow .news_gallery .swiper-slide .img2 {
      display: none !important;
    }
    .email {
      color: #fff;
      font-size: 16px;
    }
    .email:hover {
      color: #fce0b9;
    }
    @media screen and (max-width: 480px) {
      .sep-body .body_tow .news_gallery .swiper-slide .news_item {
        min-height: 500px;
      }
      .sep-body .body_tow .news_gallery .swiper-slide .img2 {
        display: block !important;
      }
      .sep-body .body_tow .news_gallery .swiper-slide .img1 {
        display: none !important;
      }
    }
  `}</style>
        <Script src="/themes/tianxing/js/all.min7839.js?v=1.2"></Script>
        {/* <Script src="/assets/js/kaka/kaka-1.0.0.js"></Script> */}
        <Script src="/assets/js/animate/wow.min.js"></Script>
        {/* <Script>new WOW().init();</Script> */}
        <noscript>Your browser does not support VBScript!</noscript>
        <Script src="/assets/js/traffic4d1a.js?t=1763192532"></Script>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=673383750668124&amp;ev=PageView&amp;noscript=1"
          />
        </noscript>
        {/* <!-- End Meta Pixel Code --> */}
        {/* <!-- Google Tag Manager (noscript) --> */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TQRM47B"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {/* <!-- End Google Tag Manager (noscript) --> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
